### ISSUE TITLE
eei return: Trap condition: unreachable

### ISSUE THREAD

**Issue by hugo-dc** [ewasm/ewasm-rust-api#1]
Getting error: `Trap condition: unreachable`

To compare, I imported the return function manually and tried to return the same data, while calling the manually imported function the test pass without errors, I realized the only difference between the manually imported function and the ewasm-rust-api function is that ewasm-api function specifies that the function never returns (using return type `-> !`). 

https://github.com/ewasm/ewasm-rust-api/blob/30112f5d75cd34e184427a3b61b514432bfd3e12/src/lib.rs#L8

**Comment by poemm** [comment]
Maybe you already know this, but the Wasm spec requires host functions to return with the type in their signature (or never return if they are in an infinite loop). So perhaps you can return in a way which triggers a Wasm trap, which allows Wasm to handle the trap and exit cleanly. This can be optimized later.

**Comment by axic** [comment]
`-> !` is added because it was made with the assumption that https://github.com/ewasm/design/issues/72 is merged

Since it is not merged, we probably should remove those atm.

**Comment by axic** [comment]
Here's a generated code example (from sha256 precompile):
```
 (func $_ZN9ewasm_api6revert17h4611de01ad540c7bE (; 74 ;) (type $7)
  (call $ethereum_revert
   (i32.const 0)
   (i32.const 0)
  )
  (unreachable)
 )
```

`-> !` means the function never returns, and it seems that Rust enforces this in the wasm output as including a trap after the function.

While this would be unnecessary since the function would never return anyway, it is a nice behaviour to ensure a non-compliant VM fails 😉 

I'd really prefer to merge https://github.com/ewasm/design/issues/72 and keep 😕

**Comment by axic** [comment]
Since the design issue was decided on and https://github.com/ewasm/hera/pull/249 was merged, this can be closed.
